apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secrets
  namespace: synctra
spec:
  provider: aws

  secretObjects:
    - secretName: backend-secrets
      type: Opaque
      data:
        - objectName: MONGO_URI
          key: MONGO_URI
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: SMTP_USER
          key: SMTP_USER
        - objectName: SMTP_PASSWORD
          key: SMTP_PASSWORD

  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "synctra/dev/backend"
        objectType: "secretsmanager"
        jmesPath:
          - path: MONGO_URI
            objectAlias: MONGO_URI
          - path: JWT_SECRET
            objectAlias: JWT_SECRET
          - path: SMTP_USER
            objectAlias: SMTP_USER
          - path: SMTP_PASSWORD
            objectAlias: SMTP_PASSWORD
